#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
   path: /
   controller: App\Controller\DefaultController::homepage

add_product:
   path: /add/product
   controller: App\Controller\ProductController::addProduct
   
register_user:
   path: /register/user
   controller: App\Controller\UserController::registerUser 
   